
export const FLIP_CARD = 'FLIP_CARD';
export const SHUFFLE_CARDS = 'SHUFFLE_CARDS';
export const RESTART_GAME = 'RESTART_GAME';
export const WIN_GAME = 'WIN_GAME';

export const FETCH_LEADERBOARD_REQUEST = 'FETCH_LEADERBOARD_REQUEST';
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_FAILURE = 'FETCH_LEADERBOARD_FAILURE';

export const STORE_SCORE_REQUEST = 'STORE_SCORE_REQUEST';
export const STORE_SCORE_SUCCESS = 'STORE_SCORE_SUCCESS';
export const STORE_SCORE_FAILURE = 'STORE_SCORE_FAILURE';

